"""Scoring constants — verified verbatim from blueprint §8.3, §8.4, §8.5.

§8.4 decision thresholds are configurable (§38) and read from settings at
import time; the defaults below match the blueprint exactly.
"""

from backend.core.config import settings
from backend.core.versions import SCORING_VERSION

# §8.3 Suggested initial weighted score (total 100)
WEIGHT_MBID_EXACT = 25.0
WEIGHT_FINGERPRINT = 25.0
WEIGHT_ARTIST_SIMILARITY = 15.0
WEIGHT_TITLE_SIMILARITY = 15.0
WEIGHT_ALBUM_SIMILARITY = 8.0
WEIGHT_DURATION_SIMILARITY = 7.0
WEIGHT_TRACK_DISC_CONSISTENCY = 3.0
WEIGHT_BARCODE_ISRC = 2.0

# §8.4 Decision thresholds (configurable via settings, blueprint §38)
AUTO_APPLY_THRESHOLD = float(settings.IDENTIFICATION_AUTO_APPLY_THRESHOLD)
AUTO_SUGGEST_REVIEW_THRESHOLD = float(settings.IDENTIFICATION_REVIEW_THRESHOLD)
REVIEW_REQUIRED_THRESHOLD = float(settings.IDENTIFICATION_REJECT_THRESHOLD)

# §8.5 Conflict penalties
PENALTY_DIFFERENT_ARTIST_STRONG_TITLE = -20.0
PENALTY_RELEASE_COUNTRY = -5.0
PENALTY_TRACK_CONTRADICTION = -10.0
PENALTY_DISC_CONTRADICTION = -10.0
PENALTY_DURATION_CONTRADICTION = -8.0
PENALTY_EDITION_REMASTER_CONTRADICTION = -5.0

# §8.3 Duration tolerance bands (seconds)
DURATION_TOLERANCE_HIGH = 1.0
DURATION_TOLERANCE_MEDIUM = 3.0
DURATION_TOLERANCE_WEAK = 7.0

# §8.4 outcome labels
AUTO_APPLY = "auto_apply"
AUTO_SUGGEST_REVIEW = "auto_suggest_review"
REVIEW_REQUIRED = "review_required"
NO_MATCH = "no_match"

__all__ = [
    "AUTO_APPLY",
    "AUTO_APPLY_THRESHOLD",
    "AUTO_SUGGEST_REVIEW",
    "AUTO_SUGGEST_REVIEW_THRESHOLD",
    "DURATION_TOLERANCE_HIGH",
    "DURATION_TOLERANCE_MEDIUM",
    "DURATION_TOLERANCE_WEAK",
    "NO_MATCH",
    "PENALTY_DIFFERENT_ARTIST_STRONG_TITLE",
    "PENALTY_DISC_CONTRADICTION",
    "PENALTY_DURATION_CONTRADICTION",
    "PENALTY_EDITION_REMASTER_CONTRADICTION",
    "PENALTY_RELEASE_COUNTRY",
    "PENALTY_TRACK_CONTRADICTION",
    "REVIEW_REQUIRED",
    "REVIEW_REQUIRED_THRESHOLD",
    "SCORING_VERSION",
    "WEIGHT_ALBUM_SIMILARITY",
    "WEIGHT_ARTIST_SIMILARITY",
    "WEIGHT_BARCODE_ISRC",
    "WEIGHT_DURATION_SIMILARITY",
    "WEIGHT_FINGERPRINT",
    "WEIGHT_MBID_EXACT",
    "WEIGHT_TITLE_SIMILARITY",
    "WEIGHT_TRACK_DISC_CONSISTENCY",
]